server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8180/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}