server:
  port: 8081

eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8180/
    instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${server.port}

spring:
  application:
    name: department-service